name: Deploy to vijay environment on push to main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-vijay-environment:
    runs-on: ubuntu-latest
    environment: vijay
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper delta detection
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      # Install sfdx-git-delta plugin
      - name: 'Installing sfdx git delta'
        run: |
          echo Y | sf plugins install sfdx-git-delta
          sf plugins --core

      # Create delta packages with better error handling
      - name: 'Create delta packages for deployment'
        run: |
          echo "Creating delta package..."
          mkdir -p changed-sources
          
          # Generate delta between current commit and previous commit
          sf sgd source delta \
            --to "HEAD" \
            --from "HEAD~1" \
            --output changed-sources/ \
            --generate-delta \
            --source force-app/
          
          echo "Delta generation completed"
          
          # Check if there are any changes to deploy
          if [ -d "changed-sources/force-app" ] && [ "$(find changed-sources/force-app -name '*.xml' -o -name '*.cls' -o -name '*.trigger' -o -name '*.page' -o -name '*.component' | wc -l)" -gt 0 ]; then
            echo "Changes detected for deployment"
            echo "DEPLOY_CHANGES=true" >> $GITHUB_ENV
            
            # List what will be deployed
            echo "Files to be deployed:"
            find changed-sources/force-app -type f | head -20
          else
            echo "No changes detected in force-app directory"
            echo "DEPLOY_CHANGES=false" >> $GITHUB_ENV
          fi

      # Deploy only if there are changes
      - name: 'Deploy to Salesforce org'
        if: env.DEPLOY_CHANGES == 'true'
        run: |
          # Create server key file
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          
          # Authenticate with Salesforce
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default
          
          # Deploy the changes
          sf project deploy start \
            --source-dir changed-sources/force-app \
            --test-level RunLocalTests \
            --wait 20
          
          # Clean up
          rm server.key

      # Skip deployment message
      - name: 'No changes to deploy'
        if: env.DEPLOY_CHANGES == 'false'
        run: |
          echo "No changes detected in the current commit compared to the previous commit."
          echo "Skipping deployment as there's nothing to deploy."